/* Spanish chrome strings. The English string IS the key; t() falls back to
   the key per entry, so a missing line renders in English. */
export const STRINGS_ES: Record<string, string> = {
  // Manual checks
  "Marked": "Marcado",
  "Open": "Abierto",
  "Ignored": "Ignorado",
  "False positive": "Falso positivo",
  "Fixed": "Corregido",
  "Marked fixed, still found": "Marcado como corregido, sigue apareciendo",
  "Checked by a person": "Comprobado por una persona",
  "section in this report": "sección en este informe",
  "sections in this report": "secciones en este informe",
  "What to fix": "Qué corregir",
  "What the law asks": "Qué exige la ley",
  "For your team": "Para su equipo",
  "Documents and other views": "Documentos y otras vistas",
  "Report": "Informe",
  "Language": "Idioma",
  "The checklist's wording changes on the next scan.": "La redacción de la lista de comprobación cambia en el próximo análisis.",
  "scan results": "resultados del análisis",
  "Scheduled scans": "Análisis programados",
  "Account": "Cuenta",
  "Signed in as": "Sesión iniciada como",
  "Key kept.": "Clave guardada.",
  "Scans from now on are saved, and the open questions can be answered.": "Los análisis se guardan a partir de ahora y se pueden responder las preguntas abiertas.",
  "Forget this key": "Olvidar esta clave",
  "Not signed in. Nothing is saved, which is the default.": "Sin sesión. No se guarda nada, que es lo predeterminado.",
  "Account key": "Clave de la cuenta",
  "Keep this key": "Guardar esta clave",
  "Checking…": "Comprobando…",
  "That is not an account key. One starts with ascan_ and is 70 characters long.": "Eso no es una clave de cuenta. Una empieza por ascan_ y tiene 70 caracteres.",
  "The server did not accept that key.": "El servidor no aceptó esa clave.",
  "open": "abiertas",
  "answered": "respondidas",
  "No software can decide these. Each one is a question about your site, not this page, so an answer holds for every later scan until you change it.": "Ningún software puede decidir esto. Cada pregunta es sobre su sitio, no sobre esta página, así que la respuesta vale para cada análisis posterior hasta que la cambie.",
  "Answers are signed and kept with their history. They fill the conformance report for buyers, which a scan alone can never complete.": "Las respuestas se firman y se conservan con su historial. Completan el informe de conformidad para compradores, que un análisis por sí solo nunca puede terminar.",
  "Answer": "Responder",
  "Change answer": "Cambiar la respuesta",
  "Your answer": "Su respuesta",
  "What you checked, in a sentence": "Qué comprobó, en una frase",
  "Goes into the conformance report as the remark for this row.": "Aparece en el informe de conformidad como observación de esta fila.",
  "Your name": "Su nombre",
  "Save answer": "Guardar la respuesta",
  "Saving…": "Guardando…",
  "Cancel": "Cancelar",
  "Sign the answer with your name. A decision nobody stands behind is not evidence.": "Firme la respuesta con su nombre. Una decisión que nadie respalda no es prueba.",
  "Could not save the answer.": "No se pudo guardar la respuesta.",
  "Could not load the open questions.": "No se pudieron cargar las preguntas abiertas.",
  "Could not load the open questions": "No se pudieron cargar las preguntas abiertas",
  "Yes. It meets this": "Sí, lo cumple",
  "No. It fails this": "No, no lo cumple",
  "Does not apply to this site": "No aplica a este sitio",
  "Looked, could not decide yet": "Revisado, aún sin decidir",
  "Officially:": "Oficialmente:",
  "Mark this finding": "Marcar este hallazgo",
  "Change the mark": "Cambiar la marca",
  "Mark as": "Marcar como",
  "Why, in a sentence": "Por qué, en una frase",
  "Save": "Guardar",
  "Sign the decision with your name.": "Firme la decisión con su nombre.",
  "Could not save the decision.": "No se pudo guardar la decisión.",
  "Scan this page automatically. If the score drops or a new finding appears, you are told.": "Analizar esta página automáticamente. Si la puntuación baja o aparece un hallazgo nuevo, se le avisa.",
  "How often": "Con qué frecuencia",
  "Every day": "Cada día",
  "Every week": "Cada semana",
  "Every 6 hours": "Cada 6 horas",
  "Email for a worse result (optional)": "Correo si el resultado empeora (opcional)",
  "Schedule it": "Programarlo",
  "Pause": "Pausar",
  "Resume": "Reanudar",
  "Delete the schedule": "Eliminar la programación",
  "Loading…": "Cargando…",
  "Paused.": "En pausa.",
  "Not run yet.": "Aún no se ha ejecutado.",
  "Runs": "Se ejecuta",
  "Last run": "Última ejecución",
  "score": "puntuación",
  "Next": "Siguiente",
  "Last run failed:": "La última ejecución falló:",
  "Writes to": "Escribe a",
  "if the score drops or a new finding appears.": "si la puntuación baja o aparece un hallazgo nuevo.",
  "The scheduler is off on this server. This schedule will not run until it is on.": "El programador está apagado en este servidor. Esta programación no se ejecutará hasta que se encienda.",
  "Mail is not set up on this server. No email will be sent.": "El correo no está configurado en este servidor. No se enviará ningún correo.",
  "Could not load the schedules.": "No se pudieron cargar las programaciones.",
  "Could not create the schedule.": "No se pudo crear la programación.",
  "Could not change the schedule.": "No se pudo cambiar la programación.",
  "Could not delete the schedule.": "No se pudo eliminar la programación.",
  "Show all": "Mostrar todo",
  "Show the first 3 only": "Mostrar solo los 3 primeros",
  "Manual checks": "Comprobaciones manuales",
  Decided: "Decidido",
  "Meets it": "Lo cumple",
  Partly: "En parte",
  "Fails it": "No lo cumple",
  "Does not apply": "No aplica",
  Undecided: "Sin decidir",
  // Section titles and nav labels
  "Your score": "Su puntuación",
  Score: "Puntuación",
  "New scan": "Nuevo análisis",
  "Since last time": "Desde la última vez",
  "Do you meet the legal standard?": "¿Cumple usted la norma legal?",
  "Legal standard": "Norma legal",
  "Ready for WCAG 2.2?": "¿Listo para WCAG 2.2?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Lo que le cuesta confianza",
  "What people can't use": "Lo que la gente no puede usar",
  "For your designer and developer": "Para su diseñador y su desarrollador",
  "Designer and developer": "Diseñador y desarrollador",
  "Notes on the design": "Notas sobre el diseño",
  "Screen reader preview": "Vista previa del lector de pantalla",
  "Accessibility statement": "Declaración de accesibilidad",
  "Conformance report": "Informe de conformidad",
  "Your page, through other eyes": "Su página, con otros ojos",
  "Through other eyes": "Con otros ojos",
  "Site audit": "Auditoría del sitio",
  "Page by page": "Página por página",
  "Pages that disagree": "Páginas que no coinciden",
  "Fix once, fix everywhere": "Arréglelo una vez, arreglado en todas partes",
  Findings: "Hallazgos",
  Sections: "Secciones",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner":
    "Empiece aquí: un lector de pantalla no puede pasar de su aviso de cookies",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "El aviso esconde la página a los lectores de pantalla y nunca recibe el foco. Hasta que eso se arregle, todo lo que hay debajo de esta línea es lo que quien usa un lector de pantalla nunca alcanza.",
  "See the finding": "Ver el hallazgo",
  // Common controls and labels
  "Show the checklist": "Mostrar la lista de comprobación",
  "Hide the checklist": "Ocultar la lista de comprobación",
  "Show fewer": "Mostrar menos",
  "Show the technical breakdown": "Mostrar el desglose técnico",
  "Hide the technical breakdown": "Ocultar el desglose técnico",
  "Learn more about this issue": "Saber más sobre este problema",
  "Start the scan": "Empezar el análisis",
  "Which site?": "¿Qué sitio?",
  "Website address (required)": "Dirección del sitio web (obligatorio)",
  "Behind a login": "Detrás de un inicio de sesión",
  "Public pages only.": "Solo páginas públicas.",
  "How much of it?": "¿Qué parte del sitio?",
  "Who reads it?": "¿Quién lo lee?",
  "Report style": "Estilo del informe",
  "For everyone": "Para todos",
  Professionals: "Profesionales",
  "Add an AI review": "Añadir una revisión con IA",
  "AI review": "Revisión con IA",
  "This page": "Esta página",
  "Whole site": "Todo el sitio",
  Severity: "Gravedad",
  Issue: "Problema",
  Instances: "Casos",
  "Affected elements": "Elementos afectados",
  "What we found": "Lo que encontramos",
  "What to do": "Qué hacer",
  "Who fixes this": "Quién lo arregla",
  "Needs a person": "Necesita una persona",
  "Would fail today": "Hoy no pasaría",
  "Nothing found": "No se encontró nada",
  "Not measured": "Sin medir",
  "Software can check it": "Un programa puede comprobarlo",
  "Fix first": "Arreglar primero",
  "Fix soon": "Arreglar pronto",
  "Fix eventually": "Arreglar más adelante",
  "Minor polish": "Retoque menor",
  "The notes": "Las notas",
  "The six new items": "Los seis puntos nuevos",
  "Save as PDF": "Guardar como PDF",
  "Email me this report": "Enviarme este informe por correo",
  "Copy summary as plain text": "Copiar el resumen como texto plano",
  "This is the order a screen reader reads it in.": "Este es el orden en que la lee un lector de pantalla.",
  // The scan form
  "Cancel. Scan without a login": "Cancelar. Analizar sin inicio de sesión",
  Fastest: "Más rápido",
  "Up to five pages from this address. Lists what repeats across them": "Hasta cinco páginas desde esta dirección. Muestra lo que se repite en todas",
  "Keep this page open. The scan runs here.":
    "Mantenga esta página abierta. El análisis se hace aquí.",
  "Most chosen": "Lo más elegido",
  "One moment…": "Un momento…",
  "Only the page at this address": "Solo la página de esta dirección",
  "Pages to check": "Páginas a comprobar",
  "What is wrong, who fixes it, and what it costs you, in plain words": "Qué está mal, quién lo corrige y qué le cuesta, en palabras sencillas",
  "Scan scope": "Alcance del análisis",
  "Each finding with its WCAG number, selector and code": "Cada hallazgo con su número WCAG, selector y código",
  // Scan narration
  "Loading your page": "Cargando su página",
  "Running the automated rules": "Ejecutando las reglas automáticas",
  "Reading the page as a screen reader announces it": "Leyendo la página tal como la anuncia un lector de pantalla",
  "Photographing the evidence": "Fotografiando las pruebas",
  "Walking every Tab stop": "Recorriendo cada parada del tabulador",
  "Enlarging the text": "Ampliando el texto",
  "Trying it at phone width": "Probándola en ancho de móvil",
  "The AI review reads the page": "La revisión con IA lee la página",
  "Writing the report": "Redactando el informe",
  "What a designer would point out, not failures against a rule. None of it counts towards the score.": "Lo que señalaría un diseñador, no incumplimientos de una regla. Nada de esto cuenta para la puntuación.",
  "Most notes are about type. Text set small, tight or in capitals loses readers before any rule is broken.": "La mayoría de las notas tratan de la tipografía. El texto pequeño, apretado o todo en mayúsculas pierde lectores antes de romper regla alguna.",
  "Which site should I check?": "¿Qué sitio reviso?",
  "Ask about the report, or name another site": "Pregunte por el informe o indique otro sitio",
  "An address is enough. Say if you want the whole site or the AI review.": "Basta con una dirección. Diga si quiere el sitio entero o la revisión con IA.",
  "Send": "Enviar",
  "You": "Usted",
  "Conversation": "Conversación",
  "Thinking…": "Pensando…",
  "Scan finished.": "Análisis terminado.",
  "The assistant is not available on this server. Paste an address and the scan still runs.": "El asistente no está disponible en este servidor. Pegue una dirección y el análisis se ejecuta igualmente.",
  "The assistant could not answer that.": "El asistente no pudo responder a eso.",
  "Use the form instead": "Usar el formulario",
  "Needed for pages behind a login.": "Necesario para páginas tras un inicio de sesión.",
  "Back to the chat": "Volver a la conversación",
  "found": "encontrados",
  "shown above.": "aparece más arriba.",
  "Not available for this scan.": "No disponible para este análisis.",
  "Try one of these:": "Pruebe uno de estos:",
  "Run a scan first: paste an address.": "Primero ejecute un análisis: pegue una dirección.",
  "Show from the report": "Mostrar del informe",
  "From an earlier scan. Run it again to see it.": "De un análisis anterior. Vuelva a ejecutarlo para verlo.",
  "Settings": "Ajustes",
  "added above.": "añadido arriba.",
  "No reply came back. Ask again.": "No llegó ninguna respuesta. Pregunte de nuevo.",
  "Could not reach the assistant. Try sending that again.": "No se pudo contactar con el asistente. Envíelo de nuevo.",
  "This conversation is too long to continue. Send your question again to start a new one.": "Esta conversación es demasiado larga para continuar. Envíe su pregunta de nuevo para empezar otra.",
  "The assistant stopped responding. Try sending that again.": "El asistente dejó de responder. Envíelo de nuevo.",
  "Assistant": "Asistente",
  "Checking {url}.": "Revisando {url}.",
  "Checked {url}.": "{url} revisado.",
  "Could not check {url}.": "No se pudo revisar {url}.",
  "The assistant is still replying. Run it again in a moment.": "El asistente todavía está respondiendo. Vuelva a intentarlo en un momento.",
  "Did not finish": "No terminó",
  "Did not run": "No se ejecutó",
  "I can't help with that here. I can check a page, or answer questions about its report.": "No puedo ayudar con eso aquí. Puedo revisar una página o responder preguntas sobre su informe.",
  "Something went wrong. Please try again.": "Algo salió mal. Inténtelo de nuevo.",
  "Web Content Accessibility Guidelines (WCAG)": "Pautas de Accesibilidad para el Contenido Web (WCAG)",
  "We check the page at an address, or up to five pages linked from it, against the {wcag} 2.1. Then we explain what to fix, in the order worth fixing it.": "Revisamos la página de una dirección, o hasta cinco páginas enlazadas desde ella, según las {wcag} 2.1. Después explicamos qué corregir, en el orden que conviene.",
  "We check the page at an address, or up to ten pages linked from it, against the {wcag} 2.1. Then we explain what to fix, in the order worth fixing it.": "Revisamos la página de una dirección, o hasta diez páginas enlazadas desde ella, según las {wcag} 2.1. Después explicamos qué corregir, en el orden que conviene.",
  "It counts the accessibility problems this scan found, weighted by how much each one costs a visitor.": "Cuenta los problemas de accesibilidad que encontró este análisis, ponderados según cuánto le cuesta cada uno a un visitante.",
  "Each severity has a limit: past it, more problems of that severity no longer lower the score.": "Cada nivel de gravedad tiene un límite: a partir de él, más problemas de ese nivel ya no bajan la puntuación.",
  "Notes on the design and misleading patterns do not count. Neither do the optional advanced level (AAA) or checks new in WCAG 2.2, the newer accessibility guidelines.": "No cuentan las notas sobre el diseño ni los patrones engañosos. Tampoco el nivel avanzado opcional (AAA) ni las novedades de las pautas de accesibilidad WCAG 2.2.",
  "When the AI review runs, its findings count too, if their card names a WCAG requirement. Those can be wrong.": "Cuando la revisión con IA se ejecuta, también cuentan sus hallazgos, si su tarjeta indica un requisito de las WCAG. Pueden ser erróneos.",
  "A scan of this kind reaches between a third and a half of accessibility problems.": "Un análisis de este tipo alcanza entre un tercio y la mitad de los problemas de accesibilidad.",
  "The rest need a person with a keyboard and a screen reader.": "El resto necesita a una persona con un teclado y un lector de pantalla.",
  "It is useful for tracking whether the site improves over time.": "Sirve para comprobar si el sitio mejora con el tiempo.",
  "It is not a statement that the site meets the law.": "No es una declaración de que el sitio cumpla la ley.",
  "What the score counts": "Qué cuenta la puntuación",
  "A scan finds what a machine can check. The rest needs a person testing the site by hand.": "Un análisis encuentra lo que una máquina puede comprobar. El resto necesita que una persona pruebe el sitio a mano.",
  "Do this first": "Haga esto primero",
  "Fixing “{title}” settles {settles} of the {outOf} most serious findings at once.": "Corregir «{title}» resuelve a la vez {settles} de los {outOf} hallazgos más graves.",
  "What a score of {band} means": "Qué significa una puntuación de {band}",
  "90 or more": "90 o más",
  "70 to 89": "70 a 89",
  "under 70": "menos de 70",
  "90 or more. Little to fix. A person would still find more.": "90 o más. Poco que corregir. Una persona aún encontraría más.",
  "70 to 89. What the scan found stops some visitors. Most get through.": "70 a 89. Lo que encontró el análisis detiene a algunos visitantes. La mayoría logra pasar.",
  "Under 70. What the scan found stops some people from using the site.": "Menos de 70. Lo que encontró el análisis impide a algunas personas usar el sitio.",
  "Scan summary": "Resumen del análisis",
  "This run": "Esta ejecución",
  "out of 100": "de 100",
  "Good": "Bien",
  "Needs work": "Necesita mejoras",
  "Failing": "Insuficiente",
  "1 issue": "1 problema",
  "{count} issues": "{count} problemas",
  "{seconds} sec": "{seconds} s",
  "Score {score} out of 100, {band}. Issues found: {count}, in {seconds} seconds.": "Puntuación {score} de 100, {band}. Problemas encontrados: {count}, en {seconds} segundos.",
  "Score {score} out of 100, {band}. Issues found: {count}.": "Puntuación {score} de 100, {band}. Problemas encontrados: {count}.",
  "Nothing here needs a fix.": "Aquí no hay nada que corregir.",
  "No.": "N.º",
  "Item": "Problema",
  "Copied": "Copiado",
  "Summary copied to the clipboard.": "Resumen copiado al portapapeles.",
  "1 issue on 1 page": "1 problema en 1 página",
  "{count} issues on 1 page": "{count} problemas en 1 página",
  "Issues by severity": "Problemas por gravedad",
  "Checked against WCAG 2.1 AA": "Revisado según las WCAG 2.1 AA",
  "1 page": "1 página",
  "{count} fix first": "Arreglar primero: {count}",
  "See the {count} findings": "Ver los {count} hallazgos",
  "Issues ({count})": "Problemas ({count})",
  "Critical": "Crítico",
  "Serious": "Grave",
  "Moderate": "Moderado",
  "Minor": "Menor",
  "No issues found ({count})": "Sin problemas encontrados ({count})",
  "Nothing here came back clean enough to list.": "Ningún criterio salió lo bastante limpio para listarlo aquí.",
  "Some checks didn't finish this time: {checks}.": "Algunas comprobaciones no terminaron esta vez: {checks}.",
  "The score above only counts what ran, so it may look better than it should. A second run usually completes them.": "La puntuación de arriba solo cuenta lo que se ejecutó, así que puede parecer mejor de lo que debería. Una segunda ejecución suele completarlas.",
  "This check ran without the AI review": "Este análisis se hizo sin la revisión con IA",
  "Not set up yet.": "Aún no está configurada.",
  "Temporarily unavailable.": "No disponible temporalmente.",
  "These findings come from automated checks only.": "Estos hallazgos proceden solo de comprobaciones automáticas.",
  "keyboard navigation": "navegación con teclado",
  "mouse-only controls": "controles solo para ratón",
  "phone layout": "diseño en el móvil",
  "text resizing": "ampliación del texto",
  "display preferences": "preferencias de visualización",
  "reading order": "orden de lectura",
  "reading level": "nivel de lectura",
  "control boundaries": "contornos de los controles",
  "state changes": "cambios de estado",
  "dark-scheme contrast": "contraste en modo oscuro",
  "phone-width contrast": "contraste en ancho de móvil",
  "screen reader names": "nombres para lectores de pantalla",
  "320px reflow": "ajuste a 320 px",
  "open dialogs": "diálogos abiertos",
  "This scan": "Este análisis",
  "Professional": "Profesional",
  "Included": "Incluida",
  "Not included": "No incluida",
  "Run again without the AI review": "Ejecutar de nuevo sin la revisión con IA",
  "Run again with the AI review": "Ejecutar de nuevo con la revisión con IA",
  "Takes another scan": "Requiere otro análisis",
  "Takes a few minutes": "Tarda unos minutos",
  "Scope": "Alcance",
  "Scan this page only": "Analizar solo esta página",
  "Scan the whole site": "Analizar todo el sitio",
};
