/* French chrome strings. The key is the English string itself; a key missing
   here falls back to that English text rather than to a blank. */
export const STRINGS_FR: Record<string, string> = {
  // Manual checks
  "Marked": "Marqué",
  "Open": "Ouvert",
  "Ignored": "Ignoré",
  "False positive": "Faux positif",
  "Fixed": "Corrigé",
  "Marked fixed, still found": "Marqué corrigé, toujours présent",
  "Checked by a person": "Vérifié par une personne",
  "section in this report": "section dans ce rapport",
  "sections in this report": "sections dans ce rapport",
  "What to fix": "À corriger",
  "What the law asks": "Ce que la loi demande",
  "For your team": "Pour votre équipe",
  "Documents and other views": "Documents et autres vues",
  "Report": "Rapport",
  "Language": "Langue",
  "The checklist's wording changes on the next scan.": "La formulation de la liste de contrôle change au prochain scan.",
  "scan results": "résultats du scan",
  "Scheduled scans": "Scans planifiés",
  "Account": "Compte",
  "Signed in as": "Connecté en tant que",
  "Key kept.": "Clé enregistrée.",
  "Scans from now on are saved, and the open questions can be answered.": "Les scans sont désormais enregistrés et les questions ouvertes peuvent recevoir une réponse.",
  "Forget this key": "Oublier cette clé",
  "Not signed in. Nothing is saved, which is the default.": "Non connecté. Rien n’est enregistré, ce qui est le réglage par défaut.",
  "Account key": "Clé du compte",
  "Keep this key": "Conserver cette clé",
  "Checking…": "Vérification…",
  "That is not an account key. One starts with ascan_ and is 70 characters long.": "Ce n’est pas une clé de compte. Une clé commence par ascan_ et compte 70 caractères.",
  "The server did not accept that key.": "Le serveur n’a pas accepté cette clé.",
  "open": "ouvertes",
  "answered": "répondues",
  "No software can decide these. Each one is a question about your site, not this page, so an answer holds for every later scan until you change it.": "Aucun logiciel ne peut trancher ces questions. Chacune porte sur votre site, pas sur cette page ; une réponse vaut donc pour chaque scan ultérieur jusqu’à ce que vous la changiez.",
  "Answers are signed and kept with their history. They fill the conformance report for buyers, which a scan alone can never complete.": "Les réponses sont signées et conservées avec leur historique. Elles complètent le rapport de conformité pour les acheteurs, qu’un scan seul ne peut jamais achever.",
  "Answer": "Répondre",
  "Change answer": "Modifier la réponse",
  "Your answer": "Votre réponse",
  "What you checked, in a sentence": "Ce que vous avez vérifié, en une phrase",
  "Goes into the conformance report as the remark for this row.": "Figure dans le rapport de conformité comme remarque pour cette ligne.",
  "Your name": "Votre nom",
  "Save answer": "Enregistrer la réponse",
  "Saving…": "Enregistrement…",
  "Cancel": "Annuler",
  "Sign the answer with your name. A decision nobody stands behind is not evidence.": "Signez la réponse de votre nom. Une décision que personne n’assume n’est pas une preuve.",
  "Could not save the answer.": "La réponse n’a pas pu être enregistrée.",
  "Could not load the open questions.": "Les questions ouvertes n’ont pas pu être chargées.",
  "Could not load the open questions": "Les questions ouvertes n’ont pas pu être chargées",
  "Yes — it meets this": "Oui, conforme",
  "No — it fails this": "Non, non conforme",
  "Does not apply to this site": "Sans objet pour ce site",
  "Looked, could not decide yet": "Examiné, pas encore tranché",
  "Officially:": "Officiellement :",
  "Mark this finding": "Marquer ce constat",
  "Change the mark": "Modifier la marque",
  "Mark as": "Marquer comme",
  "Why, in a sentence": "Pourquoi, en une phrase",
  "Save": "Enregistrer",
  "Sign the decision with your name.": "Signez la décision de votre nom.",
  "Could not save the decision.": "La décision n’a pas pu être enregistrée.",
  "Scan this page automatically. If the score drops or a new finding appears, you are told.": "Scanner cette page automatiquement. Si le score baisse ou qu’un nouveau constat apparaît, vous êtes prévenu.",
  "How often": "À quelle fréquence",
  "Every day": "Chaque jour",
  "Every week": "Chaque semaine",
  "Every 6 hours": "Toutes les 6 heures",
  "Email for a worse result (optional)": "E-mail en cas de résultat moins bon (facultatif)",
  "Schedule it": "Planifier",
  "Pause": "Suspendre",
  "Resume": "Reprendre",
  "Delete the schedule": "Supprimer la planification",
  "Loading…": "Chargement…",
  "Paused.": "Suspendu.",
  "Not run yet.": "Pas encore exécuté.",
  "Runs": "S’exécute",
  "Last run": "Dernière exécution",
  "score": "score",
  "Next": "Prochain",
  "Last run failed:": "Dernière exécution en échec :",
  "Writes to": "Écrit à",
  "if the score drops or a new finding appears.": "si le score baisse ou qu’un nouveau constat apparaît.",
  "The scheduler is off on this server. This schedule will not run until it is on.": "Le planificateur est désactivé sur ce serveur. Cette planification ne s’exécutera pas tant qu’il ne l’est pas.",
  "Mail is not set up on this server. No email will be sent.": "L’e-mail n’est pas configuré sur ce serveur. Aucun e-mail ne sera envoyé.",
  "Could not load the schedules.": "Les planifications n’ont pas pu être chargées.",
  "Could not create the schedule.": "La planification n’a pas pu être créée.",
  "Could not change the schedule.": "La planification n’a pas pu être modifiée.",
  "Could not delete the schedule.": "La planification n’a pas pu être supprimée.",
  "Show all": "Tout afficher",
  "Show the first 3 only": "Afficher les 3 premiers seulement",
  "Manual checks": "Vérifications manuelles",
  Decided: "Décidé",
  "Meets it": "Conforme",
  Partly: "En partie",
  "Fails it": "Non conforme",
  "Does not apply": "Sans objet",
  Undecided: "Non tranché",
  // Section titles and nav labels
  "Your score": "Votre score",
  Score: "Score",
  "New scan": "Nouvelle analyse",
  "Since last time": "Depuis la dernière fois",
  "Do you meet the legal standard?": "Respectez-vous la norme légale ?",
  "Legal standard": "Norme légale",
  "Ready for WCAG 2.2?": "Prêt pour WCAG 2.2 ?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Ce qui vous coûte la confiance",
  "What people can't use": "Ce que les gens ne peuvent pas utiliser",
  "For your designer and developer": "Pour votre designer et votre développeur",
  "Designer and developer": "Designer et développeur",
  "Notes on the design": "Remarques sur le design",
  "Screen reader preview": "Aperçu au lecteur d'écran",
  "Accessibility statement": "Déclaration d'accessibilité",
  "Conformance report": "Rapport de conformité",
  "Your page, through other eyes": "Votre page, vue par d'autres yeux",
  "Through other eyes": "Par d'autres yeux",
  "Site audit": "Audit du site",
  "Page by page": "Page par page",
  "Pages that disagree": "Pages qui divergent",
  "Fix once, fix everywhere": "Corrigez une fois, corrigé partout",
  Findings: "Constats",
  Sections: "Sections",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner":
    "Commencez ici : un lecteur d'écran ne peut pas franchir votre bannière cookies",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "La bannière masque la page aux lecteurs d'écran et ne prend jamais le focus. Tant que ce n'est pas corrigé, tout ce qui suit cette ligne est ce qu'un utilisateur de lecteur d'écran n'atteint jamais.",
  "See the finding": "Voir le constat",
  // Common controls and labels
  "Show the checklist": "Afficher la liste de contrôle",
  "Hide the checklist": "Masquer la liste de contrôle",
  "Show fewer": "En afficher moins",
  "Show the technical breakdown": "Afficher le détail technique",
  "Hide the technical breakdown": "Masquer le détail technique",
  "Learn more about this issue": "En savoir plus sur ce problème",
  "Start the scan": "Lancer l'analyse",
  "Which site?": "Quel site ?",
  "Website address (required)": "Adresse du site (obligatoire)",
  "Behind a login": "Derrière une connexion",
  "Public pages only.": "Pages publiques uniquement.",
  "How much of it?": "Quelle étendue ?",
  "Who reads it?": "Qui le lit ?",
  "Report style": "Style du rapport",
  "For everyone": "Pour tout le monde",
  Professionals: "Professionnels",
  "Add an AI review": "Ajouter une relecture par IA",
  "AI review": "Relecture par IA",
  "This page": "Cette page",
  "Whole site": "Tout le site",
  Severity: "Gravité",
  Issue: "Problème",
  Instances: "Occurrences",
  "Affected elements": "Éléments concernés",
  "What we found": "Ce que nous avons trouvé",
  "What to do": "Que faire",
  "Who fixes this": "Qui corrige cela",
  "Needs a person": "À vérifier par une personne",
  "Would fail today": "Échouerait aujourd'hui",
  "Nothing found": "Rien trouvé",
  "Not measured": "Non mesuré",
  "Software can check it": "Un logiciel peut le vérifier",
  "Fix first": "À corriger en premier",
  "Fix soon": "À corriger bientôt",
  "Fix eventually": "À corriger plus tard",
  "Minor polish": "Finition mineure",
  "The notes": "Les remarques",
  "The six new items": "Les six nouveautés",
  "Save as PDF": "Enregistrer en PDF",
  "Email me this report": "M'envoyer ce rapport par courriel",
  "Copy summary as plain text": "Copier le résumé en texte brut",
  "This is the order a screen reader reads it in.": "C’est l’ordre dans lequel un lecteur d’écran lit la page.",
  // The scan form
  "Cancel — scan without a login": "Annuler — analyser sans connexion",
  Fastest: "Le plus rapide",
  "Finds what repeats everywhere": "Trouve ce qui se répète partout",
  "Keep this page open — the scan runs here.":
    "Gardez cette page ouverte — l'analyse se déroule ici.",
  "Most chosen": "Le plus choisi",
  "One moment…": "Un instant…",
  "One page, end to end": "Une page, de bout en bout",
  "Pages to check": "Pages à analyser",
  "Plain-language summary and costs": "Résumé en langage clair et coûts",
  "Scan scope": "Étendue de l'analyse",
  "WCAG-mapped technical findings": "Constats techniques par critère WCAG",
};
