/* Spanish chrome strings. The English string IS the key; t() falls back to
   the key per entry, so a missing line renders in English. */
export const STRINGS_ES: Record<string, string> = {
  // Section titles and nav labels
  "Your score": "Su puntuación",
  Score: "Puntuación",
  "New scan": "Nuevo análisis",
  "Since last time": "Desde la última vez",
  "Do you meet the legal standard?": "¿Cumple usted la norma legal?",
  "Legal standard": "Norma legal",
  "Ready for WCAG 2.2?": "¿Listo para WCAG 2.2?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Lo que le cuesta confianza",
  "What people can't use": "Lo que la gente no puede usar",
  "For your designer and developer": "Para su diseñador y su desarrollador",
  "Designer and developer": "Diseñador y desarrollador",
  "Notes on the design": "Notas sobre el diseño",
  "Screen reader preview": "Vista previa del lector de pantalla",
  "Accessibility statement": "Declaración de accesibilidad",
  "Conformance report": "Informe de conformidad",
  "Your page, through other eyes": "Su página, con otros ojos",
  "Through other eyes": "Con otros ojos",
  "Site audit": "Auditoría del sitio",
  "Page by page": "Página por página",
  "Pages that disagree": "Páginas que no coinciden",
  "Fix once, fix everywhere": "Arréglelo una vez, arreglado en todas partes",
  Findings: "Hallazgos",
  Sections: "Secciones",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner":
    "Empiece aquí: un lector de pantalla no puede pasar de su aviso de cookies",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "El aviso esconde la página a los lectores de pantalla y nunca recibe el foco. Hasta que eso se arregle, todo lo que hay debajo de esta línea es lo que quien usa un lector de pantalla nunca alcanza.",
  "See the finding": "Ver el hallazgo",
  // Common controls and labels
  "Show the checklist": "Mostrar la lista de comprobación",
  "Hide the checklist": "Ocultar la lista de comprobación",
  "Show fewer": "Mostrar menos",
  "Show the technical breakdown": "Mostrar el desglose técnico",
  "Hide the technical breakdown": "Ocultar el desglose técnico",
  "Learn more about this issue": "Saber más sobre este problema",
  "Start the scan": "Empezar el análisis",
  "Which site?": "¿Qué sitio?",
  "Website address (required)": "Dirección del sitio web (obligatorio)",
  "Behind a login": "Detrás de un inicio de sesión",
  "Public pages only.": "Solo páginas públicas.",
  "How much of it?": "¿Qué parte del sitio?",
  "Who reads it?": "¿Quién lo lee?",
  "Report style": "Estilo del informe",
  "For everyone": "Para todos",
  Professionals: "Profesionales",
  "Add an AI review": "Añadir una revisión con IA",
  "AI review": "Revisión con IA",
  "This page": "Esta página",
  "Whole site": "Todo el sitio",
  Severity: "Gravedad",
  Issue: "Problema",
  Instances: "Casos",
  "Affected elements": "Elementos afectados",
  "What we found": "Lo que encontramos",
  "What to do": "Qué hacer",
  "Who fixes this": "Quién lo arregla",
  "Officially:": "Oficialmente:",
  "Needs a person": "Necesita una persona",
  "Would fail today": "Hoy no pasaría",
  "Nothing found": "No se encontró nada",
  "Not measured": "Sin medir",
  "Software can check it": "Un programa puede comprobarlo",
  "Fix first": "Arreglar primero",
  "Fix soon": "Arreglar pronto",
  "Fix eventually": "Arreglar más adelante",
  "Minor polish": "Retoque menor",
  "The notes": "Las notas",
  "The six new items": "Los seis puntos nuevos",
  "Save as PDF": "Guardar como PDF",
  "Email me this report": "Enviarme este informe por correo",
  "Copy summary as plain text": "Copiar el resumen como texto plano",
  "Reading order, not visual order.": "Orden de lectura, no orden visual.",
  // The scan form
  "Cancel — scan without a login": "Cancelar — analizar sin inicio de sesión",
  Fastest: "Más rápido",
  "Finds what repeats everywhere": "Encuentra lo que se repite en todas partes",
  "Keep this page open — the scan runs here.":
    "Mantenga esta página abierta — el análisis se hace aquí.",
  "Most chosen": "Lo más elegido",
  "One moment…": "Un momento…",
  "One page, end to end": "Una página, de principio a fin",
  "Pages to check": "Páginas a comprobar",
  "Plain-language summary and costs": "Resumen en lenguaje sencillo y costes",
  "Scan scope": "Alcance del análisis",
  "WCAG-mapped technical findings": "Hallazgos técnicos vinculados a WCAG",
};
