/* Deutsche Fassung der Rahmen-Texte. Schlüssel ist der englische String. */
export const STRINGS_DE: Record<string, string> = {
  // Manuelle Prüfungen
  "Marked": "Markiert",
  "Open": "Offen",
  "Ignored": "Ignoriert",
  "False positive": "Fehlalarm",
  "Fixed": "Behoben",
  "Marked fixed, still found": "Als behoben markiert, weiterhin gefunden",
  "Checked by a person": "Von einer Person geprüft",
  "section in this report": "Abschnitt in diesem Bericht",
  "sections in this report": "Abschnitte in diesem Bericht",
  "What to fix": "Was zu beheben ist",
  "What the law asks": "Was das Gesetz verlangt",
  "For your team": "Für Ihr Team",
  "Documents and other views": "Dokumente und andere Ansichten",
  "Report": "Bericht",
  "Language": "Sprache",
  "The checklist's wording changes on the next scan.": "Die Formulierung der Checkliste ändert sich beim nächsten Scan.",
  "scan results": "Scan-Ergebnisse",
  "Scheduled scans": "Geplante Scans",
  "Account": "Konto",
  "Signed in as": "Angemeldet als",
  "Key kept.": "Schlüssel gespeichert.",
  "Scans from now on are saved, and the open questions can be answered.": "Scans werden ab jetzt gespeichert, und die offenen Fragen können beantwortet werden.",
  "Forget this key": "Schlüssel vergessen",
  "Not signed in. Nothing is saved, which is the default.": "Nicht angemeldet. Nichts wird gespeichert – das ist die Voreinstellung.",
  "Account key": "Kontoschlüssel",
  "Keep this key": "Schlüssel behalten",
  "Checking…": "Wird geprüft …",
  "That is not an account key. One starts with ascan_ and is 70 characters long.": "Das ist kein Kontoschlüssel. Einer beginnt mit ascan_ und ist 70 Zeichen lang.",
  "The server did not accept that key.": "Der Server hat diesen Schlüssel nicht akzeptiert.",
  "open": "offen",
  "answered": "beantwortet",
  "No software can decide these. Each one is a question about your site, not this page, so an answer holds for every later scan until you change it.": "Keine Software kann diese Fragen entscheiden. Jede betrifft Ihre Website, nicht diese Seite – eine Antwort gilt daher für jeden späteren Scan, bis Sie sie ändern.",
  "Answers are signed and kept with their history. They fill the conformance report for buyers, which a scan alone can never complete.": "Antworten werden unterschrieben und mit ihrem Verlauf aufbewahrt. Sie füllen den Konformitätsbericht für Käufer aus, den ein Scan allein nie vervollständigen kann.",
  "Answer": "Beantworten",
  "Change answer": "Antwort ändern",
  "Your answer": "Ihre Antwort",
  "What you checked, in a sentence": "Was Sie geprüft haben, in einem Satz",
  "Goes into the conformance report as the remark for this row.": "Erscheint im Konformitätsbericht als Anmerkung zu dieser Zeile.",
  "Your name": "Ihr Name",
  "Save answer": "Antwort speichern",
  "Saving…": "Wird gespeichert …",
  "Cancel": "Abbrechen",
  "Sign the answer with your name. A decision nobody stands behind is not evidence.": "Unterschreiben Sie die Antwort mit Ihrem Namen. Eine Entscheidung, hinter der niemand steht, ist kein Nachweis.",
  "Could not save the answer.": "Die Antwort konnte nicht gespeichert werden.",
  "Could not load the open questions.": "Die offenen Fragen konnten nicht geladen werden.",
  "Could not load the open questions": "Die offenen Fragen konnten nicht geladen werden",
  "Yes — it meets this": "Ja – erfüllt",
  "No — it fails this": "Nein – nicht erfüllt",
  "Does not apply to this site": "Trifft auf diese Website nicht zu",
  "Looked, could not decide yet": "Geprüft, noch nicht entschieden",
  "Officially:": "Offiziell:",
  "Mark this finding": "Diesen Befund markieren",
  "Change the mark": "Markierung ändern",
  "Mark as": "Markieren als",
  "Why, in a sentence": "Warum, in einem Satz",
  "Save": "Speichern",
  "Sign the decision with your name.": "Unterschreiben Sie die Entscheidung mit Ihrem Namen.",
  "Could not save the decision.": "Die Entscheidung konnte nicht gespeichert werden.",
  "Scan this page automatically. If the score drops or a new finding appears, you are told.": "Diese Seite automatisch scannen. Fällt der Wert oder erscheint ein neuer Befund, werden Sie benachrichtigt.",
  "How often": "Wie oft",
  "Every day": "Jeden Tag",
  "Every week": "Jede Woche",
  "Every 6 hours": "Alle 6 Stunden",
  "Email for a worse result (optional)": "E-Mail bei schlechterem Ergebnis (optional)",
  "Schedule it": "Einplanen",
  "Pause": "Pausieren",
  "Resume": "Fortsetzen",
  "Delete the schedule": "Zeitplan löschen",
  "Loading…": "Wird geladen …",
  "Paused.": "Pausiert.",
  "Not run yet.": "Noch nicht gelaufen.",
  "Runs": "Läuft",
  "Last run": "Letzter Lauf",
  "score": "Wert",
  "Next": "Nächster",
  "Last run failed:": "Letzter Lauf fehlgeschlagen:",
  "Writes to": "Schreibt an",
  "if the score drops or a new finding appears.": "wenn der Wert fällt oder ein neuer Befund erscheint.",
  "The scheduler is off on this server. This schedule will not run until it is on.": "Der Zeitplaner ist auf diesem Server ausgeschaltet. Dieser Zeitplan läuft erst, wenn er eingeschaltet ist.",
  "Mail is not set up on this server. No email will be sent.": "E-Mail ist auf diesem Server nicht eingerichtet. Es wird keine E-Mail gesendet.",
  "Could not load the schedules.": "Die Zeitpläne konnten nicht geladen werden.",
  "Could not create the schedule.": "Der Zeitplan konnte nicht angelegt werden.",
  "Could not change the schedule.": "Der Zeitplan konnte nicht geändert werden.",
  "Could not delete the schedule.": "Der Zeitplan konnte nicht gelöscht werden.",
  "Show all": "Alle anzeigen",
  "Show the first 3 only": "Nur die ersten 3 anzeigen",
  "Manual checks": "Manuelle Prüfungen",
  Decided: "Entschieden",
  "Meets it": "Erfüllt",
  Partly: "Teilweise",
  "Fails it": "Nicht erfüllt",
  "Does not apply": "Trifft nicht zu",
  Undecided: "Offen",
  // Abschnittstitel und Navigation
  "Your score": "Ihr Ergebnis",
  Score: "Ergebnis",
  "New scan": "Neuer Scan",
  "Since last time": "Seit dem letzten Mal",
  "Do you meet the legal standard?": "Erfüllen Sie den gesetzlichen Standard?",
  "Legal standard": "Gesetzlicher Standard",
  "Ready for WCAG 2.2?": "Bereit für WCAG 2.2?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Was Sie Vertrauen kostet",
  "What people can't use": "Was Menschen nicht nutzen können",
  "For your designer and developer": "Für Ihren Designer und Entwickler",
  "Designer and developer": "Designer und Entwickler",
  "Notes on the design": "Hinweise zur Gestaltung",
  "Screen reader preview": "Screenreader-Vorschau",
  "Accessibility statement": "Erklärung zur Barrierefreiheit",
  "Conformance report": "Konformitätsbericht",
  "Your page, through other eyes": "Ihre Seite mit anderen Augen",
  "Through other eyes": "Mit anderen Augen",
  "Site audit": "Website-Prüfung",
  "Page by page": "Seite für Seite",
  "Pages that disagree": "Seiten, die sich widersprechen",
  "Fix once, fix everywhere": "Einmal beheben, überall behoben",
  Findings: "Befunde",
  Sections: "Abschnitte",
  // Die Eilmeldung
  "Start here: a screen reader cannot get past your cookie banner": "Hier anfangen: Ein Screenreader kommt an Ihrem Cookie-Banner nicht vorbei",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.": "Das Banner versteckt die Seite vor Screenreadern und nimmt nie den Fokus. Bis das behoben ist, ist alles unter dieser Linie das, was Screenreader-Nutzer nie erreichen.",
  "See the finding": "Zum Befund",
  // Bedienelemente und Beschriftungen
  "Show the checklist": "Checkliste zeigen",
  "Hide the checklist": "Checkliste ausblenden",
  "Show fewer": "Weniger zeigen",
  "Show the technical breakdown": "Technische Fassung zeigen",
  "Hide the technical breakdown": "Technische Fassung ausblenden",
  "Learn more about this issue": "Mehr zu diesem Problem erfahren",
  "Start the scan": "Scan starten",
  "Which site?": "Welche Website?",
  "Website address (required)": "Adresse der Website (Pflichtfeld)",
  "Behind a login": "Hinter einem Login",
  "Public pages only.": "Nur öffentliche Seiten.",
  "How much of it?": "Wie viel davon?",
  "Who reads it?": "Wer liest ihn?",
  "Report style": "Art des Berichts",
  "For everyone": "Für alle",
  Professionals: "Fachleute",
  "Add an AI review": "KI-Prüfung hinzufügen",
  "AI review": "KI-Prüfung",
  "This page": "Diese Seite",
  "Whole site": "Ganze Website",
  Severity: "Schweregrad",
  Issue: "Problem",
  Instances: "Vorkommen",
  "Affected elements": "Betroffene Elemente",
  "What we found": "Was wir gefunden haben",
  "What to do": "Was zu tun ist",
  "Who fixes this": "Wer das behebt",
  "Needs a person": "Braucht einen Menschen",
  "Would fail today": "Würde heute durchfallen",
  "Nothing found": "Nichts gefunden",
  "Not measured": "Nicht gemessen",
  "Software can check it": "Software kann das prüfen",
  "Fix first": "Zuerst beheben",
  "Fix soon": "Bald beheben",
  "Fix eventually": "Irgendwann beheben",
  "Minor polish": "Kleiner Schliff",
  "The notes": "Die Hinweise",
  "The six new items": "Die sechs neuen Punkte",
  "Save as PDF": "Als PDF speichern",
  "Email me this report": "Bericht per E-Mail schicken",
  "Copy summary as plain text": "Zusammenfassung als Text kopieren",
  "This is the order a screen reader reads it in.": "In dieser Reihenfolge liest ein Screenreader die Seite.",
  // Das Scan-Formular
  "Cancel \u2014 scan without a login": "Abbrechen – ohne Login scannen",
  Fastest: "Am schnellsten",
  "Finds what repeats everywhere": "Findet, was sich überall wiederholt",
  "Keep this page open \u2014 the scan runs here.": "Lassen Sie diese Seite offen – der Scan läuft hier.",
  "Most chosen": "Am häufigsten gewählt",
  "One moment\u2026": "Einen Moment…",
  "One page, end to end": "Eine Seite, von A bis Z",
  "Pages to check": "Zu prüfende Seiten",
  "Plain-language summary and costs": "Verständliche Zusammenfassung und Kosten",
  "Scan scope": "Umfang des Scans",
  "WCAG-mapped technical findings": "Technische Befunde nach WCAG",
};
