/* Spanish chrome strings. The English string IS the key; t() falls back to
   the key per entry, so a missing line renders in English. */
export const STRINGS_ES: Record<string, string> = {
  // Manual checks
  "Marked": "Marcado",
  "Open": "Abierto",
  "Ignored": "Ignorado",
  "False positive": "Falso positivo",
  "Fixed": "Corregido",
  "Marked fixed, still found": "Marcado como corregido, sigue apareciendo",
  "Checked by a person": "Comprobado por una persona",
  "section in this report": "sección en este informe",
  "sections in this report": "secciones en este informe",
  "What to fix": "Qué corregir",
  "What the law asks": "Qué exige la ley",
  "For your team": "Para su equipo",
  "Documents and other views": "Documentos y otras vistas",
  "Report": "Informe",
  "Language": "Idioma",
  "The checklist's wording changes on the next scan.": "La redacción de la lista de comprobación cambia en el próximo análisis.",
  "scan results": "resultados del análisis",
  "Scheduled scans": "Análisis programados",
  "Account": "Cuenta",
  "Signed in as": "Sesión iniciada como",
  "Key kept.": "Clave guardada.",
  "Scans from now on are saved, and the open questions can be answered.": "Los análisis se guardan a partir de ahora y se pueden responder las preguntas abiertas.",
  "Forget this key": "Olvidar esta clave",
  "Not signed in. Nothing is saved, which is the default.": "Sin sesión. No se guarda nada, que es lo predeterminado.",
  "Account key": "Clave de la cuenta",
  "Keep this key": "Guardar esta clave",
  "Checking…": "Comprobando…",
  "That is not an account key. One starts with ascan_ and is 70 characters long.": "Eso no es una clave de cuenta. Una empieza por ascan_ y tiene 70 caracteres.",
  "The server did not accept that key.": "El servidor no aceptó esa clave.",
  "open": "abiertas",
  "answered": "respondidas",
  "No software can decide these. Each one is a question about your site, not this page, so an answer holds for every later scan until you change it.": "Ningún software puede decidir esto. Cada pregunta es sobre su sitio, no sobre esta página, así que la respuesta vale para cada análisis posterior hasta que la cambie.",
  "Answers are signed and kept with their history. They fill the conformance report for buyers, which a scan alone can never complete.": "Las respuestas se firman y se conservan con su historial. Completan el informe de conformidad para compradores, que un análisis por sí solo nunca puede terminar.",
  "Answer": "Responder",
  "Change answer": "Cambiar la respuesta",
  "Your answer": "Su respuesta",
  "What you checked, in a sentence": "Qué comprobó, en una frase",
  "Goes into the conformance report as the remark for this row.": "Aparece en el informe de conformidad como observación de esta fila.",
  "Your name": "Su nombre",
  "Save answer": "Guardar la respuesta",
  "Saving…": "Guardando…",
  "Cancel": "Cancelar",
  "Sign the answer with your name. A decision nobody stands behind is not evidence.": "Firme la respuesta con su nombre. Una decisión que nadie respalda no es prueba.",
  "Could not save the answer.": "No se pudo guardar la respuesta.",
  "Could not load the open questions.": "No se pudieron cargar las preguntas abiertas.",
  "Could not load the open questions": "No se pudieron cargar las preguntas abiertas",
  "Yes. It meets this": "Sí, lo cumple",
  "No. It fails this": "No, no lo cumple",
  "Does not apply to this site": "No aplica a este sitio",
  "Looked, could not decide yet": "Revisado, aún sin decidir",
  "Officially:": "Oficialmente:",
  "Mark this finding": "Marcar este hallazgo",
  "Change the mark": "Cambiar la marca",
  "Mark as": "Marcar como",
  "Why, in a sentence": "Por qué, en una frase",
  "Save": "Guardar",
  "Sign the decision with your name.": "Firme la decisión con su nombre.",
  "Could not save the decision.": "No se pudo guardar la decisión.",
  "Scan this page automatically. If the score drops or a new finding appears, you are told.": "Analizar esta página automáticamente. Si la puntuación baja o aparece un hallazgo nuevo, se le avisa.",
  "How often": "Con qué frecuencia",
  "Every day": "Cada día",
  "Every week": "Cada semana",
  "Every 6 hours": "Cada 6 horas",
  "Email for a worse result (optional)": "Correo si el resultado empeora (opcional)",
  "Schedule it": "Programarlo",
  "Pause": "Pausar",
  "Resume": "Reanudar",
  "Delete the schedule": "Eliminar la programación",
  "Loading…": "Cargando…",
  "Paused.": "En pausa.",
  "Not run yet.": "Aún no se ha ejecutado.",
  "Runs": "Se ejecuta",
  "Last run": "Última ejecución",
  "score": "puntuación",
  "Next": "Siguiente",
  "Last run failed:": "La última ejecución falló:",
  "Writes to": "Escribe a",
  "if the score drops or a new finding appears.": "si la puntuación baja o aparece un hallazgo nuevo.",
  "The scheduler is off on this server. This schedule will not run until it is on.": "El programador está apagado en este servidor. Esta programación no se ejecutará hasta que se encienda.",
  "Mail is not set up on this server. No email will be sent.": "El correo no está configurado en este servidor. No se enviará ningún correo.",
  "Could not load the schedules.": "No se pudieron cargar las programaciones.",
  "Could not create the schedule.": "No se pudo crear la programación.",
  "Could not change the schedule.": "No se pudo cambiar la programación.",
  "Could not delete the schedule.": "No se pudo eliminar la programación.",
  "Show all": "Mostrar todo",
  "Show the first 3 only": "Mostrar solo los 3 primeros",
  "Manual checks": "Comprobaciones manuales",
  Decided: "Decidido",
  "Meets it": "Lo cumple",
  Partly: "En parte",
  "Fails it": "No lo cumple",
  "Does not apply": "No aplica",
  Undecided: "Sin decidir",
  // Section titles and nav labels
  "Your score": "Su puntuación",
  Score: "Puntuación",
  "New scan": "Nuevo análisis",
  "Since last time": "Desde la última vez",
  "Do you meet the legal standard?": "¿Cumple usted la norma legal?",
  "Legal standard": "Norma legal",
  "Ready for WCAG 2.2?": "¿Listo para WCAG 2.2?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Lo que le cuesta confianza",
  "What people can't use": "Lo que la gente no puede usar",
  "For your designer and developer": "Para su diseñador y su desarrollador",
  "Designer and developer": "Diseñador y desarrollador",
  "Notes on the design": "Notas sobre el diseño",
  "Screen reader preview": "Vista previa del lector de pantalla",
  "Accessibility statement": "Declaración de accesibilidad",
  "Conformance report": "Informe de conformidad",
  "Your page, through other eyes": "Su página, con otros ojos",
  "Through other eyes": "Con otros ojos",
  "Site audit": "Auditoría del sitio",
  "Page by page": "Página por página",
  "Pages that disagree": "Páginas que no coinciden",
  "Fix once, fix everywhere": "Arréglelo una vez, arreglado en todas partes",
  Findings: "Hallazgos",
  Sections: "Secciones",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner":
    "Empiece aquí: un lector de pantalla no puede pasar de su aviso de cookies",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "El aviso esconde la página a los lectores de pantalla y nunca recibe el foco. Hasta que eso se arregle, todo lo que hay debajo de esta línea es lo que quien usa un lector de pantalla nunca alcanza.",
  "See the finding": "Ver el hallazgo",
  // Common controls and labels
  "Show the checklist": "Mostrar la lista de comprobación",
  "Hide the checklist": "Ocultar la lista de comprobación",
  "Show fewer": "Mostrar menos",
  "Show the technical breakdown": "Mostrar el desglose técnico",
  "Hide the technical breakdown": "Ocultar el desglose técnico",
  "Learn more about this issue": "Saber más sobre este problema",
  "Start the scan": "Empezar el análisis",
  "Which site?": "¿Qué sitio?",
  "Website address (required)": "Dirección del sitio web (obligatorio)",
  "Behind a login": "Detrás de un inicio de sesión",
  "Public pages only.": "Solo páginas públicas.",
  "How much of it?": "¿Qué parte del sitio?",
  "Who reads it?": "¿Quién lo lee?",
  "Report style": "Estilo del informe",
  "For everyone": "Para todos",
  Professionals: "Profesionales",
  "Add an AI review": "Añadir una revisión con IA",
  "AI review": "Revisión con IA",
  "This page": "Esta página",
  "Whole site": "Todo el sitio",
  Severity: "Gravedad",
  Issue: "Problema",
  Instances: "Casos",
  "Affected elements": "Elementos afectados",
  "What we found": "Lo que encontramos",
  "What to do": "Qué hacer",
  "Who fixes this": "Quién lo arregla",
  "Needs a person": "Necesita una persona",
  "Would fail today": "Hoy no pasaría",
  "Nothing found": "No se encontró nada",
  "Not measured": "Sin medir",
  "Software can check it": "Un programa puede comprobarlo",
  "Fix first": "Arreglar primero",
  "Fix soon": "Arreglar pronto",
  "Fix eventually": "Arreglar más adelante",
  "Minor polish": "Retoque menor",
  "The notes": "Las notas",
  "The six new items": "Los seis puntos nuevos",
  "Save as PDF": "Guardar como PDF",
  "Email me this report": "Enviarme este informe por correo",
  "Copy summary as plain text": "Copiar el resumen como texto plano",
  "This is the order a screen reader reads it in.": "Este es el orden en que la lee un lector de pantalla.",
  // The scan form
  "Cancel. Scan without a login": "Cancelar. Analizar sin inicio de sesión",
  Fastest: "Más rápido",
  "Up to five pages from this address. Lists what repeats across them": "Hasta cinco páginas desde esta dirección. Muestra lo que se repite en todas",
  "Keep this page open. The scan runs here.":
    "Mantenga esta página abierta. El análisis se hace aquí.",
  "Most chosen": "Lo más elegido",
  "One moment…": "Un momento…",
  "Only the page at this address": "Solo la página de esta dirección",
  "Pages to check": "Páginas a comprobar",
  "What is wrong, who fixes it, and what it costs you, in plain words": "Qué está mal, quién lo corrige y qué le cuesta, en palabras sencillas",
  "Scan scope": "Alcance del análisis",
  "Each finding with its WCAG number, selector and code": "Cada hallazgo con su número WCAG, selector y código",
};
