/**
 * The report's chrome, as a dictionary. Content copy (finding titles,
 * explanations, asks, fixes) lives in wcagPlain and its per-language
 * siblings; THIS file carries the shell a reader sees around it — section
 * titles, buttons, table heads, the stop-press.
 *
 * `t(key)` returns the current language's string, falling back to English
 * per key: a missing translation degrades to the English label, never to a
 * blank or a key name. Keys are the English strings themselves — the report
 * is written in its keys, so a key that goes stale is visible in the UI
 * rather than silently orphaned in a map.
 */
import { getLang, type Lang } from "./i18n";
import { STRINGS_DE } from "./strings.de";
import { STRINGS_ES } from "./strings.es";
import { STRINGS_FR } from "./strings.fr";

const BY_LANG: Partial<Record<Lang, Record<string, string>>> = {
  de: STRINGS_DE,
  es: STRINGS_ES,
  fr: STRINGS_FR,
};

export function t(key: string): string {
  const lang = getLang();
  if (lang === "en") return key;
  return BY_LANG[lang]?.[key] ?? key;
}

/**
 * Every chrome string the components route through t(), listed so the
 * translation files can be checked for parity in tests. The English value
 * IS the key.
 */
export const CHROME_KEYS: string[] = [
  // Manual checks (guided manual testing)
  "Language",
  "The checklist's wording changes on the next scan.",
  "scan results",
  "Scheduled scans",
  "Manual checks",
  "Show all",
  "Show the first 3 only",
  "Account",
  "Signed in as",
  "Key kept.",
  "Scans from now on are saved, and the open questions can be answered.",
  "Forget this key",
  "Not signed in. Nothing is saved, which is the default.",
  "Account key",
  "Keep this key",
  "Checking…",
  "That is not an account key. One starts with ascan_ and is 70 characters long.",
  "The server did not accept that key.",
  "open",
  "answered",
  "No software can decide these. Each one is a question about your site, not this page, so an answer holds for every later scan until you change it.",
  "Answers are signed and kept with their history. They fill the conformance report for buyers, which a scan alone can never complete.",
  "Answer",
  "Change answer",
  "Your answer",
  "What you checked, in a sentence",
  "Goes into the conformance report as the remark for this row.",
  "Your name",
  "Save answer",
  "Saving…",
  "Cancel",
  "Sign the answer with your name. A decision nobody stands behind is not evidence.",
  "Could not save the answer.",
  "Could not load the open questions.",
  "Could not load the open questions",
  "Yes. It meets this",
  "No. It fails this",
  "Does not apply to this site",
  "Looked, could not decide yet",
  "Officially:",
  "Mark this finding",
  "Change the mark",
  "Mark as",
  "Why, in a sentence",
  "Save",
  "Sign the decision with your name.",
  "Could not save the decision.",
  "Scan this page automatically. If the score drops or a new finding appears, you are told.",
  "How often",
  "Every day",
  "Every week",
  "Every 6 hours",
  "Email for a worse result (optional)",
  "Schedule it",
  "Pause",
  "Resume",
  "Delete the schedule",
  "Loading…",
  "Paused.",
  "Not run yet.",
  "Runs",
  "Last run",
  "score",
  "Next",
  "Last run failed:",
  "Writes to",
  "if the score drops or a new finding appears.",
  "The scheduler is off on this server. This schedule will not run until it is on.",
  "Mail is not set up on this server. No email will be sent.",
  "Could not load the schedules.",
  "Could not create the schedule.",
  "Could not change the schedule.",
  "Could not delete the schedule.",
  "Checked by a person",
  "Marked",
  "Open",
  "Ignored",
  "False positive",
  "Fixed",
  "Marked fixed, still found",
  "Decided",
  "Meets it",
  "Partly",
  "Fails it",
  "Does not apply",
  "Undecided",
  // Section titles and nav labels
  "Your score",
  "Score",
  "New scan",
  "Since last time",
  "Do you meet the legal standard?",
  "Legal standard",
  "Ready for WCAG 2.2?",
  "WCAG 2.2",
  "What costs you trust",
  "What people can't use",
  "For your designer and developer",
  "Designer and developer",
  "Notes on the design",
  "Screen reader preview",
  "Accessibility statement",
  "Conformance report",
  "Your page, through other eyes",
  "Through other eyes",
  "Site audit",
  "Page by page",
  "Pages that disagree",
  "Fix once, fix everywhere",
  "Findings",
  "Sections",
  "What to fix",
  "What the law asks",
  "For your team",
  "Documents and other views",
  "Report",
  "section in this report",
  "sections in this report",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.",
  "See the finding",
  // Common controls and labels
  "Show the checklist",
  "Hide the checklist",
  "Show fewer",
  "Show the technical breakdown",
  "Hide the technical breakdown",
  "Learn more about this issue",
  "Start the scan",
  "Which site?",
  "Website address (required)",
  "Behind a login",
  "Public pages only.",
  "How much of it?",
  "Who reads it?",
  "Report style",
  "For everyone",
  "Professionals",
  "Add an AI review",
  "AI review",
  "This page",
  "Whole site",
  "Severity",
  "Issue",
  "Instances",
  "Affected elements",
  "What we found",
  "What to do",
  "Who fixes this",
  "Needs a person",
  "Would fail today",
  "Nothing found",
  "Not measured",
  "Software can check it",
  "Fix first",
  "Fix soon",
  "Fix eventually",
  "Minor polish",
  "The notes",
  "The six new items",
  "Save as PDF",
  "Email me this report",
  "Copy summary as plain text",
  "This is the order a screen reader reads it in.",
  /* The scan form — the first thing anyone reads, and until the
     languages landed the one part that stayed English in all of
     them. */
  "Cancel. Scan without a login",
  "Fastest",
  "Up to five pages from this address. Lists what repeats across them",
  "Keep this page open. The scan runs here.",
  "Most chosen",
  "One moment\u2026",
  "Only the page at this address",
  "Pages to check",
  "What is wrong, who fixes it, and what it costs you, in plain words",
  "Scan scope",
  "Each finding with its WCAG number, selector and code",
];
