/* French chrome strings. The key is the English string itself; a key missing
   here falls back to that English text rather than to a blank. */
export const STRINGS_FR: Record<string, string> = {
  // Section titles and nav labels
  "Your score": "Votre score",
  Score: "Score",
  "New scan": "Nouvelle analyse",
  "Since last time": "Depuis la dernière fois",
  "Do you meet the legal standard?": "Respectez-vous la norme légale ?",
  "Legal standard": "Norme légale",
  "Ready for WCAG 2.2?": "Prêt pour WCAG 2.2 ?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Ce qui vous coûte la confiance",
  "What people can't use": "Ce que les gens ne peuvent pas utiliser",
  "For your designer and developer": "Pour votre designer et votre développeur",
  "Designer and developer": "Designer et développeur",
  "Notes on the design": "Remarques sur le design",
  "Screen reader preview": "Aperçu au lecteur d'écran",
  "Accessibility statement": "Déclaration d'accessibilité",
  "Conformance report": "Rapport de conformité",
  "Your page, through other eyes": "Votre page, vue par d'autres yeux",
  "Through other eyes": "Par d'autres yeux",
  "Site audit": "Audit du site",
  "Page by page": "Page par page",
  "Pages that disagree": "Pages qui divergent",
  "Fix once, fix everywhere": "Corrigez une fois, corrigé partout",
  Findings: "Constats",
  Sections: "Sections",
  // The stop-press
  "Start here: a screen reader cannot get past your cookie banner":
    "Commencez ici : un lecteur d'écran ne peut pas franchir votre bannière cookies",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "La bannière masque la page aux lecteurs d'écran et ne prend jamais le focus. Tant que ce n'est pas corrigé, tout ce qui suit cette ligne est ce qu'un utilisateur de lecteur d'écran n'atteint jamais.",
  "See the finding": "Voir le constat",
  // Common controls and labels
  "Show the checklist": "Afficher la liste de contrôle",
  "Hide the checklist": "Masquer la liste de contrôle",
  "Show fewer": "En afficher moins",
  "Show the technical breakdown": "Afficher le détail technique",
  "Hide the technical breakdown": "Masquer le détail technique",
  "Learn more about this issue": "En savoir plus sur ce problème",
  "Start the scan": "Lancer l'analyse",
  "Which site?": "Quel site ?",
  "Website address (required)": "Adresse du site (obligatoire)",
  "Behind a login": "Derrière une connexion",
  "Public pages only.": "Pages publiques uniquement.",
  "How much of it?": "Quelle étendue ?",
  "Who reads it?": "Qui le lit ?",
  "Report style": "Style du rapport",
  "Business owners": "Chefs d'entreprise",
  Professionals: "Professionnels",
  "Add an AI review": "Ajouter une relecture par IA",
  "AI review": "Relecture par IA",
  "This page": "Cette page",
  "Whole site": "Tout le site",
  Severity: "Gravité",
  Issue: "Problème",
  Instances: "Occurrences",
  "Affected elements": "Éléments concernés",
  "What we found": "Ce que nous avons trouvé",
  "What to do": "Que faire",
  "Who fixes this": "Qui corrige cela",
  "Officially:": "Officiellement :",
  "Needs a person": "À vérifier par une personne",
  "Would fail today": "Échouerait aujourd'hui",
  "Nothing found": "Rien trouvé",
  "Software can check it": "Un logiciel peut le vérifier",
  "Fix first": "À corriger en premier",
  "Fix soon": "À corriger bientôt",
  "Fix eventually": "À corriger plus tard",
  "Minor polish": "Finition mineure",
  "The notes": "Les remarques",
  "The six new items": "Les six nouveautés",
  "Save as PDF": "Enregistrer en PDF",
  "Email me this report": "M'envoyer ce rapport par courriel",
  "Copy summary as plain text": "Copier le résumé en texte brut",
  "Reading order, not visual order.": "Ordre de lecture, pas ordre visuel.",
  // The scan form
  "Cancel — scan without a login": "Annuler — analyser sans connexion",
  Fastest: "Le plus rapide",
  "Finds what repeats everywhere": "Trouve ce qui se répète partout",
  "Keep this page open — the scan runs here.":
    "Gardez cette page ouverte — l'analyse se déroule ici.",
  "Most chosen": "Le plus choisi",
  "One moment…": "Un instant…",
  "One page, end to end": "Une page, de bout en bout",
  "Pages to check": "Pages à analyser",
  "Plain-language summary and costs": "Résumé en langage clair et coûts",
  "Scan scope": "Étendue de l'analyse",
  "WCAG-mapped technical findings": "Constats techniques par critère WCAG",
};
