/* Deutsche Fassung der Rahmen-Texte. Schlüssel ist der englische String. */
export const STRINGS_DE: Record<string, string> = {
  // Abschnittstitel und Navigation
  "Your score": "Ihr Ergebnis",
  Score: "Ergebnis",
  "New scan": "Neuer Scan",
  "Since last time": "Seit dem letzten Mal",
  "Do you meet the legal standard?": "Erfüllen Sie den gesetzlichen Standard?",
  "Legal standard": "Gesetzlicher Standard",
  "Ready for WCAG 2.2?": "Bereit für WCAG 2.2?",
  "WCAG 2.2": "WCAG 2.2",
  "What costs you trust": "Was Sie Vertrauen kostet",
  "What people can't use": "Was Menschen nicht nutzen können",
  "For your designer and developer": "Für Ihren Designer und Entwickler",
  "Designer and developer": "Designer und Entwickler",
  "Notes on the design": "Hinweise zur Gestaltung",
  "Screen reader preview": "Screenreader-Vorschau",
  "Accessibility statement": "Erklärung zur Barrierefreiheit",
  "Conformance report": "Konformitätsbericht",
  "Your page, through other eyes": "Ihre Seite mit anderen Augen",
  "Through other eyes": "Mit anderen Augen",
  "Site audit": "Website-Prüfung",
  "Page by page": "Seite für Seite",
  "Pages that disagree": "Seiten, die sich widersprechen",
  "Fix once, fix everywhere": "Einmal beheben, überall behoben",
  Findings: "Befunde",
  Sections: "Abschnitte",
  // Die Eilmeldung
  "Start here: a screen reader cannot get past your cookie banner":
    "Hier anfangen: Ein Screenreader kommt an Ihrem Cookie-Banner nicht vorbei",
  "The banner hides the page from screen readers and never takes focus. Until that is fixed, everything below this line is what a screen reader user never reaches.":
    "Das Banner versteckt die Seite vor Screenreadern und nimmt nie den Fokus. Bis das behoben ist, ist alles unter dieser Linie das, was Screenreader-Nutzer nie erreichen.",
  "See the finding": "Zum Befund",
  // Bedienelemente und Beschriftungen
  "Show the checklist": "Checkliste zeigen",
  "Hide the checklist": "Checkliste ausblenden",
  "Show fewer": "Weniger zeigen",
  "Show the technical breakdown": "Technische Fassung zeigen",
  "Hide the technical breakdown": "Technische Fassung ausblenden",
  "Learn more about this issue": "Mehr zu diesem Problem erfahren",
  "Start the scan": "Scan starten",
  "Which site?": "Welche Website?",
  "Website address (required)": "Adresse der Website (Pflichtfeld)",
  "Behind a login": "Hinter einem Login",
  "Public pages only.": "Nur öffentliche Seiten.",
  "How much of it?": "Wie viel davon?",
  "Who reads it?": "Wer liest ihn?",
  "Report style": "Art des Berichts",
  "Business owners": "Unternehmer",
  Professionals: "Fachleute",
  "Add an AI review": "KI-Prüfung hinzufügen",
  "AI review": "KI-Prüfung",
  "This page": "Diese Seite",
  "Whole site": "Ganze Website",
  Severity: "Schweregrad",
  Issue: "Problem",
  Instances: "Vorkommen",
  "Affected elements": "Betroffene Elemente",
  "What we found": "Was wir gefunden haben",
  "What to do": "Was zu tun ist",
  "Who fixes this": "Wer das behebt",
  "Officially:": "Offiziell:",
  "Needs a person": "Braucht einen Menschen",
  "Would fail today": "Würde heute durchfallen",
  "Nothing found": "Nichts gefunden",
  "Software can check it": "Software kann das prüfen",
  "Fix first": "Zuerst beheben",
  "Fix soon": "Bald beheben",
  "Fix eventually": "Irgendwann beheben",
  "Minor polish": "Kleiner Schliff",
  "The notes": "Die Hinweise",
  "The six new items": "Die sechs neuen Punkte",
  "Save as PDF": "Als PDF speichern",
  "Email me this report": "Bericht per E-Mail schicken",
  "Copy summary as plain text": "Zusammenfassung als Text kopieren",
  "Reading order, not visual order.": "Lesereihenfolge, nicht die sichtbare Reihenfolge.",
};
